# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/torch-toolbox

    steps:
      - checkout
      # run tests!
      # https://pytest.org
      - run:
          name: install pytorch
          command: |
            sudo pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
            pip3 install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
      - run:
          name: install pytest
          command: |
            pip install pytest
      - run:
          name: run tests
          command: |
            pytest tests

      - store_artifacts:
          path: test-reports
          destination: test-reports